title: Katalon Store Docs
github:
  another_url: https://github.com/katalon-plugin-docs
description: All the documentation to successfully install, configure and manage your Katalon plugins.
show_downloads: true
google_analytics: UA-81802338-14
theme: jekyll-theme-cayman
